// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ss_proto.proto

package ss_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd int32

const (
	Cmd_NONE         Cmd = 0
	Cmd_SS_PING_PONG Cmd = 1
	Cmd_SS_ROLE_LOAD Cmd = 2
)

var Cmd_name = map[int32]string{
	0: "NONE",
	1: "SS_PING_PONG",
	2: "SS_ROLE_LOAD",
}

var Cmd_value = map[string]int32{
	"NONE":         0,
	"SS_PING_PONG": 1,
	"SS_ROLE_LOAD": 2,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

func (Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5348236be6d05af3, []int{0}
}

type PingPong struct {
	Gid                  int64    `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Seq                  int32    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPong) Reset()         { *m = PingPong{} }
func (m *PingPong) String() string { return proto.CompactTextString(m) }
func (*PingPong) ProtoMessage()    {}
func (*PingPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_5348236be6d05af3, []int{0}
}

func (m *PingPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPong.Unmarshal(m, b)
}
func (m *PingPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPong.Marshal(b, m, deterministic)
}
func (m *PingPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPong.Merge(m, src)
}
func (m *PingPong) XXX_Size() int {
	return xxx_messageInfo_PingPong.Size(m)
}
func (m *PingPong) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPong.DiscardUnknown(m)
}

var xxx_messageInfo_PingPong proto.InternalMessageInfo

func (m *PingPong) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *PingPong) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PingPong) GetValueByKey(key string) interface{} {
	switch key {
	case "gid":
		return m.GetGid()
	case "seq":
		return m.GetSeq()
	}
	return nil
}

func (m *PingPong) SetValueByKey(key string, value interface{}) {
	switch key {
	case "gid":
		m.Gid = value.(int64)
	case "seq":
		m.Seq = value.(int32)
	}
}

type RoleLoad struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Base                 []byte   `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleLoad) Reset()         { *m = RoleLoad{} }
func (m *RoleLoad) String() string { return proto.CompactTextString(m) }
func (*RoleLoad) ProtoMessage()    {}
func (*RoleLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_5348236be6d05af3, []int{1}
}

func (m *RoleLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleLoad.Unmarshal(m, b)
}
func (m *RoleLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleLoad.Marshal(b, m, deterministic)
}
func (m *RoleLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleLoad.Merge(m, src)
}
func (m *RoleLoad) XXX_Size() int {
	return xxx_messageInfo_RoleLoad.Size(m)
}
func (m *RoleLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleLoad.DiscardUnknown(m)
}

var xxx_messageInfo_RoleLoad proto.InternalMessageInfo

func (m *RoleLoad) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleLoad) GetBase() []byte {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *RoleLoad) GetValueByKey(key string) interface{} {
	switch key {
	case "roleId":
		return m.GetRoleId()
	case "base":
		return m.GetBase()
	}
	return nil
}

func (m *RoleLoad) SetValueByKey(key string, value interface{}) {
	switch key {
	case "roleId":
		m.RoleId = value.(int64)
	case "base":
		m.Base = value.([]byte)
	}
}

var SS_PROTO_structType = map[string]interface{}{
	"PingPong": PingPong{},
	"RoleLoad": RoleLoad{},
}

func init() {
	proto.RegisterEnum("Cmd", Cmd_name, Cmd_value)
	proto.RegisterType((*PingPong)(nil), "PingPong")
	proto.RegisterType((*RoleLoad)(nil), "RoleLoad")
}

func init() { proto.RegisterFile("ss_proto.proto", fileDescriptor_5348236be6d05af3) }

var fileDescriptor_5348236be6d05af3 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x8e, 0x2f,
	0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x4a, 0x7a, 0x5c, 0x1c, 0x01, 0x99, 0x79, 0xe9, 0x01,
	0xf9, 0x79, 0xe9, 0x42, 0x02, 0x5c, 0xcc, 0xe9, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc,
	0x41, 0x20, 0x26, 0x48, 0xa4, 0x38, 0xb5, 0x50, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc4,
	0x54, 0x32, 0xe3, 0xe2, 0x08, 0xca, 0xcf, 0x49, 0xf5, 0xc9, 0x4f, 0x4c, 0x11, 0x12, 0xe3, 0x62,
	0x2b, 0xca, 0xcf, 0x49, 0xf5, 0x84, 0x69, 0x81, 0xf2, 0x84, 0x84, 0xb8, 0x58, 0x92, 0x12, 0x8b,
	0x53, 0xc1, 0xda, 0x78, 0x82, 0xc0, 0x6c, 0x2d, 0x63, 0x2e, 0x66, 0xe7, 0xdc, 0x14, 0x21, 0x0e,
	0x2e, 0x16, 0x3f, 0x7f, 0x3f, 0x57, 0x01, 0x06, 0x21, 0x01, 0x2e, 0x9e, 0xe0, 0xe0, 0xf8, 0x00,
	0x4f, 0x3f, 0xf7, 0xf8, 0x00, 0x7f, 0x3f, 0x77, 0x01, 0x46, 0xa8, 0x48, 0x90, 0xbf, 0x8f, 0x6b,
	0xbc, 0x8f, 0xbf, 0xa3, 0x8b, 0x00, 0x93, 0x13, 0x57, 0x14, 0x07, 0xcc, 0xb9, 0x49, 0x6c, 0x60,
	0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x4b, 0x11, 0xdd, 0xc1, 0x00, 0x00, 0x00,
}
