// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roletbl.proto

package roletbl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tbl struct {
	RoleId               *int64   `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
	RoleName             *string  `protobuf:"bytes,2,opt,name=roleName" json:"roleName,omitempty"`
	Level                *int32   `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tbl) Reset()         { *m = Tbl{} }
func (m *Tbl) String() string { return proto.CompactTextString(m) }
func (*Tbl) ProtoMessage()    {}
func (*Tbl) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9cba4fceee75f29, []int{0}
}

func (m *Tbl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tbl.Unmarshal(m, b)
}
func (m *Tbl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tbl.Marshal(b, m, deterministic)
}
func (m *Tbl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tbl.Merge(m, src)
}
func (m *Tbl) XXX_Size() int {
	return xxx_messageInfo_Tbl.Size(m)
}
func (m *Tbl) XXX_DiscardUnknown() {
	xxx_messageInfo_Tbl.DiscardUnknown(m)
}

var xxx_messageInfo_Tbl proto.InternalMessageInfo

func (m *Tbl) GetRoleId() int64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *Tbl) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *Tbl) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Tbl) GetValueByKey(key string) interface{} {
	switch key {
	case "roleId":
		return m.GetRoleId()
	case "roleName":
		return m.GetRoleName()
	case "level":
		return m.GetLevel()
	}
	return nil
}

func (m *Tbl) SetValueByKey(key string, value interface{}) {
	switch key {
	case "roleId":
		m.RoleId = value.(*int64)
	case "roleName":
		m.RoleName = value.(*string)
	case "level":
		m.Level = value.(*int32)
	}
}

var ROLETBL_structType = map[string]interface{}{
	"Tbl": Tbl{},
}

func init() {
	proto.RegisterType((*Tbl)(nil), "roletbl.tbl")
}

func init() { proto.RegisterFile("roletbl.proto", fileDescriptor_f9cba4fceee75f29) }

var fileDescriptor_f9cba4fceee75f29 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xca, 0xcf, 0x49,
	0x2d, 0x49, 0xca, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xfc, 0xb9,
	0x98, 0x4b, 0x92, 0x72, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x22, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xcc, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x07, 0x88, 0xe5, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x0b, 0x89, 0x70, 0xb1, 0xe6, 0xa4, 0x96, 0xa5, 0xe6,
	0x48, 0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x38, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0x44, 0x61, 0x29, 0x69, 0x00, 0x00, 0x00,
}
